config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "home/about" => "home#about"
  resources :books
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title, presence: true
 validates :body, presence: true,
  length: {maximum: 200}
 belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true,
   length: {minimum: 2, maximum: 20}


 has_many :books, dependent: :destroy

 attachment :profile_image

 validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @list = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
       redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = 'You have creatad book successfully.'
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if current_user.id == @book.user_id
      if @book.update(book_params)
        redirect_to @book
        flash[:notice] ='You have updated book successfully.'
      else
        render 'edit'
      end
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if current_user.id == @user.id
      if @user.update(user_params)
        redirect_to user_path(@user)
        flash[:notice] = 'You have updated user successfully.'
      else
        render 'edit'
      end
    else
      redirect_to user_path(current_user.id)
    end
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1>
            Editing Book
          </h1>
          <% if @book.errors.any? %>
          <h3>
            <%= @book.errors.count %>errors prohibited this obj from being saved:
          </h3>
          <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          <% end %>
          <%= form_with model: @book, local:true do |f| %>
          <div class="field row">
            <label for="book_title">Title</label></br>
            <%= f.text_field :title, class: "col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <label for="book_body">Opinion</label><br>
            <%= f.text_area :body,class: "col-xs-12 book_body" %>
          </div><br>
          <div class="actions row">
            <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
          </div><br>
          <div class="text">
            <%= link_to 'Show', book_path(@book.id),class: "" %>
            |
            <a class="back" href="/books">Back</a>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>

app/views/books/index.html.erb
<body>
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
            <table class="table">
              <tbody>
                <tr><%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png", size:'100x100' %></tr>
                <tr>
                  <th>name</th>
                  <td><%= current_user.name %></td>
                </tr>
                <tr>
                  <th>introduction</th>
                  <td><%= current_user.introduction %></td>
                </tr>
              </tbody>
            </table>
            <div class="row">
             <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            </div>

      <h2>New book</h2>
      <%= form_with model: @book, local:true do |f| %>
       <div class="box">
          <label for="book_title">Title</label><br>
          <%= f.text_field :title %>
        </div>
        <div class="box">
          <label for="book_opinion">Opinion</label><br>
          <%= f.text_area :body %>
        </div>
      <div class="box">
      <%= f.submit 'Create Book' %>
      </div>
    <% end %>
  </div>

  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      <div class="table">
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user_id) do %><%= attachment_image_tag book.user, :profile_image, fallback: "no-image.png", size:'40x40' %><% end %></td>
          <td><%= link_to book.title, book_path(book.id)  %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
        <tbody>
       </div>
    </table>
  </div>
</body>

app/views/books/show.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
      <h2>User info</h2>
        <table class="table">
          <tbody>
            <tr><%= attachment_image_tag @book.user, :profile_image, fallback: "no-image.png", size:'100x100' %></tr>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
               <th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-xs-3">
          <h2>New book</h2>
          <%= form_with model: @list, local:true do |f| %>
          <div class="box">
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
          </div>
          <div class="box">
            <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
          </div>
          <div class="box">
            <%= f.submit 'Create Book' %>
          </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-xs-9">
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <tr></tr>
            <div class="table">
              <tbody>
              <tr>
                <td><%= attachment_image_tag @book.user,  :profile_image, fallback: "no-image.png", size:'40x40' %>
                 <br><%= link_to user_path(@book.user) do %><%= @book.user.name %><% end %></td>
                <td><%= @book.title %></td>
                <td><%= @book.body %></td>
                <% if @book.user_id == current_user.id %>
                <td><%= link_to 'Edit', edit_book_path(@book),class: "" %></td>
                <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？？" %></td>
                <% end %>
              </tr>
              <tbody>
            </div>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/home/about.html.erb
  <body>
    <section class="section">
      <div class="container">
        <div class="row">
          <h2>welcome to
          <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers!</strong></h2>
          </span>
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </section>
  </body>

app/views/home/index.html.erb
  <body>
    <div class="container">
      <div class="row">
        <div class="top-message col-md-offset-3 col-md-6">
          <h1>welcome to
            <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers  !!</strong>
            </span>
          </h1>
          <p>In
            <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers,</strong></span><br/>
            you can share and exchange your opinions , inpressions , and emotions<br/>
            about various books!
          </p>
          <div class="btn-wrapper">
            <div class="row1">
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %><br>
          </div>
          <div class="row1">
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
          </div>
        </div>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <header>

    <div class="container">
      <span class="title">Bookers</span>
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
              <div class="sidemenu">
                <%= link_to user_path(current_user) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true">Home </span>
                <% end %>
              </div>
              <div class="sidemenu">
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true">Users  </span>
                  <% end %>
              </div>
              <div class="sidemenu">
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true">Books  </span>
                <% end %>
              </div>
              <div class="sidemenu">
                  <%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-share' %>
              </div>
              <% else %>
              <div class="sidemenu">
                <%= link_to "Home", root_path, class: "glyphicon glyphicon-home" %>
                 <!-- <span class="glyphicon glyphicon-home" aria-hidden="true">Home  </span>-->
              </div>
              <div class="sidemenu">
              <%= link_to "About",  home_about_path, class: "glyphicon glyphicon-link" %>
              </div>
              <div class="sidemenu">
                 <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
              </div>
              <div class="sidemenu">
                <%= link_to "login", user_session_path, class: "glyphicon glyphicon-log-in" %>
              </div>
            <% end %>
          </ul>


        </div>
      </div>
    </header>


  <body>
     <div class="container">
        <% if flash[:notice] %>
        <div class="notification is-info">
          <p class="notice"><%= notice %></p>
        </div>
        <% end %>

        <% if flash[:alert] %>
        <div class="notification is-danger">
          <p class="alert"><%= alert %></p>
        </div>
        <% end %>
      </body>
    <%= yield %>
</body>
</html>

app/views/users/edit.html.erb
  <body>
    <div class="container">
      <h2>
        User info
      </h2>
        <% if @user.errors.any? %>
      <h3>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
      </h3>
        <% @user.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
        <% end %>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="box">
          <label for="user_name">Name</label>
          <%= f.text_field :name %>
        </div>
        <div class="row">
          <div class="col-sm-12">Image
            <%= f.attachment_field :profile_image %>
          </div>
        </div>
        <div class="box">
          <label for="user_body">Introduction</label>
          <%= f.text_area :introduction %>
        </div>
        <div class="box">
          <%= f.submit 'Update User' %>
        </div>
      <% end %>
    </div>
  </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>

app/views/users/index.html.erb
<body>
  <% if @book.errors.any? %>
    <h1> error </h1>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
          <table class="table">
            <tbody>
              <tr><%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png", size:'100x100' %></tr>
              <tr>
                <th>name</th>
                <td><%= current_user.name %></td>
              </tr>
              <tr>
                <th>introduction</th>
                <td><%= current_user.introduction %></td>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
          </div>

          <h2>New book</h2>
          <%= form_with model: @book, local:true do |f| %>
            <div class="box">
              <label for="book_title">Title</label><br>
              <%= f.text_field :title %>
            </div>
            <div class="box">
              <label for="book_opinion">Opinion</label><br>
               <%= f.text_area :body %>
            </div>
          <div class="box">
          <%= f.submit 'Create Book' %>
          </div>
          <% end %>
        </div>

        <div class="col-xs-9">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
              </tr>
            <div class="table">
              <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: "no-image.png", size:'40x40' %></td>
                <td><%= user.name %></td>
                <td><%= user.introduction %></td>
                <td><%= link_to 'Show',user_path(user),class: "" %></td>
              </tr>
              <% end %>
              <tbody>
            </div>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<body>
   <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
      <h2>User info</h2>
        <table class="table">
          <tbody>
            <tr><%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", size:'100x100' %></tr>
            <tr>
              <th>name</th>
            　<td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </tbody>
        </table>
        <div class="row">
           <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
        </div>

        <h2>New book</h2>
        <%= form_with model: @book, local:true do |f| %>
        <div class="box">
          <label for="book_title">Title</label><br>
          <%= f.text_field :title %>
        </div>
        <div class="box">
          <label for="book_opinion">Opinion</label><br>
          <%= f.text_area :body %>
        </div>
        <div class="box">
        <%= f.submit 'Create Book' %>
        </div>
        <% end %>
      </div>

      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <tr>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
          <div class="table">
            <tbody>
            <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, fallback: "no-image.png", size:'40x40' %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
            <tbody>
          </div>
        </table>
      </div>
    </div>
  </div>
</body>